sudo: false
language: python

matrix:
    include:
        - os: linux
          python: 3.6
        - os: osx
          language: generic

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update -q; brew upgrade -q python; fi
    - pip install tox-travis

script: tox
