sudo: false
language: python

matrix:
    include:
        - os: linux
          python: 3.6
        - os: osx
          language: generic

before_script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
        chmod +x ./cc-test-reporter;
        ./cc-test-reporter before-build;
      fi

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update -q; brew upgrade -q python; fi
    - pip install tox-travis

script: tox

after_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

env:
  global:
    - secure: KhCgDGPWK6aQeLuRZiCF97yKA1W0MAROPmjwakt3mv8tpsU86b5cu1YJsfgQdx2qgA1+/18NiXFYLhOXMnkUBofA+FqizcIQ4pEdfJ0el
    lqsN5rNCAKUxH8K0jSEKHAm+SQt9rUx7RHNY6M3qVmuuDNr3qrec2reYNVj4Vf5p9m3/i58Te0zMsRk0NlLSB4eeAhEj9IcfQFxAoSupvILfDmNhy7kV
    CHeDNFD1Dc2bvy69jov8YSrL5iPTfZhbX6JlwcVX9HiL5HgUgC8uuuAa73dj+SS1lgxpw7K9eanzhdQD1dnRnrpU1TswA3OD5CNP9wuzTzIDf8KcXXUe
    K9jjNEvMW/BQtZzxaLHqDlB/Xn2cxDk9qbQ0Ei/cdkNygwXFgw+4F24lDhEvjluTUPPHp2dP7Iz1U5+nu87YOp/XZfoeRf8xhgHKnnknvWUbDqKlMw66
    eG4edQNxpSAjtSUgktzN44VOIcSK9JFd4qlDI38/HedctfC1FYlObYS/ikflQXFGodR21rhHbJH2k8cTvkDYn7tr2EzMQizUv2iuA9bbuIfwNeussMOV
    u/zvRXwt2Wr60g3uVN8deA1twMKWQSVvI+KA8VOkWiy0AOSxYRGgJacZB6rVgxNS1C1TH4jsIV/L2f0sRpzHrxyGH/GjNprJBCQwOjBK4z5eGFoJRY=
