package:
 name: rama
 version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}

source:
 git_url: ../../

build:
 number: 0

requirements:
 build:
  - python 3.6.*
 run:
  - python 3.6.*
  - astropy
  - lxml
  - numpy
  - matplotlib
  - requests

test:
  imports:
    - rama
