package:
 name: rama
 version: 0.1.0

source:
 path: ../../

build:
 number: 1

requirements:
 build:
  - python 3.6.*
 run:
  - python 3.6.*
  - astropy
  - lxml
  - numpy
  - matplotlib
  - requests

test:
  imports:
    - rama
